### ISSUE TITLE
Page doesn't display after login

### ISSUE THREAD

**Issue by sebastian** [hellonoam/notern#1]
After you have logged in, the login form doesn't change to the list view

**Comment by hellonoam** [comment]
bit more details would be nice. You mean on any device?

**Comment by sebastian** [comment]
All browsers actually.
When I am logged out I get the login screen.
Then after a random set of clicks on the different login buttons I usually get the red circle of fail around the text boxes but I never get to the main page.
When refreshing the whole site I am all of a sudden logged in...

**Comment by hellonoam** [comment]
that's weird, the login/signup works as expected for me. was this on
production?

**Comment by sebastian** [comment]
Yes, that is on the production version.

~ Sebastian

**Comment by sebastian** [comment]
Ok, I see what is going on! :)
My account had been flushed since the db must have been reset or something. Hence when I tried logging in, it failed. Yet when I refreshed the site I was logged in, although with a non-existant account :D

Now that I recreated the account, it still has all my original notes, which is nice :)

~ Sebastian

**Comment by sebastian** [comment]
Opened a new issue (#11) for the new bug
