### ISSUE TITLE
refreshing the page after logon shows different notes

### ISSUE THREAD

**Issue by hellonoam** [hellonoam/notern#10]
sometimes after posting notes and refreshing the page, the website doesn't load any notes, even though they are in the localstorage. However sometimes adding a new note triggers the 'showing' of all notes

**Comment by sebastian** [comment]
This is very strange.
Adding a new note should not trigger the display of old notes at all. They are handled completely separately!
Each old note is rendered individually, and the new note added is just added to the top of the list.

Needs investigation.
Is it reproducible?

**Comment by hellonoam** [comment]
doesn't seem to happen again. but refreshing the page sometimes makes all
the notes disappear

**Comment by sebastian** [comment]
That is really strange.
I have never had that problem.
Can you reset your localstorage and see if you can still get the same behavior? (assuming the latest client side code is being used of course! 

~ Sebastian

**Comment by hellonoam** [comment]
last time I pushed was yesterday at 6, have you pushed anything since?

**Comment by hellonoam** [comment]
aha! only happens in Chrome not in Firefox

**Comment by sebastian** [comment]
Yes, I added bug fixes last night

~ Sebastian

**Comment by hellonoam** [comment]
either you didn't push it or you did before 6.

**Comment by sebastian** [comment]
This is one of the commits:
https://github.com/hellonoam/notern/commit/1d6b159fbc7ebae93d99cb5e35b0c04874a10001

Committed shortly before 22:00

~ Sebastian

**Comment by hellonoam** [comment]
still getting no notes after refreshing the page a couple of times in
chrome

**Comment by sebastian** [comment]
And there is nothing in the logs when it is happening?
I can't manage to reproduce it :(

~ Sebastian

**Comment by hellonoam** [comment]
why would there be, server side is working as expected. The client is
getting all the notes but just not presenting them

**Comment by sebastian** [comment]
I meant client side logs.
So here is the procedure as it is happening in the code:
Create NoteController.
Notern listens to new notes being added
Notern loads all notes from the localStorage and adds them one by one
Then it loads the server notes and unless they are present in the local notes variable they are added and then rendered...
A new note only adds it to the local note controller self.notes variable and then renders it... I don't understand what is going on in the buggy case!

I wish I could reproduce it. What does your local storage look like?
What happens when all local storage and caches and all are flushed?

~ Sebastian

**Comment by hellonoam** [comment]
can't seem to reproduce now, must have been fixed with one of the last
commits. It looks usable to me now. what do you think should we start
advertising it?

**Comment by sebastian** [comment]
Before we start advertising:
- We should get the offline mode working. I have already needed it a couple of times!
- We should add some metric framework like http://www.kissmetrics.com/ and http://mixpanel.com/

The offline moving part has two steps to it:
- Move reverse geocoding to the server
- Add yahoo stylesheet to the notern.com server

~ Sebastian

**Comment by hellonoam** [comment]
what do you mean by adding yahoo stylesheet to the server?
I've added google analytics but maybe mixpanel would be better

**Comment by sebastian** [comment]
Yes, let's skip google analytics.
Google analytics doesn't give us much of interest in terms of the usage of our client side app.

What I meant with the yahoo thing was to store the stylesheet directly on our server

~ Sebastian

**Comment by sebastian** [comment]
Marking this issue as resolved
