### ISSUE TITLE
hide show jquery functions do not work on mobile platforms

### ISSUE THREAD

**Issue by hellonoam** [hellonoam/notern#9]
the hide and show functions on DOM objects don't actually work on mobile devices hence the whole site doesn't work on mobiles

**Comment by sebastian** [comment]
Can you expand a bit on this?
It works well both on my iPad and iPhone

**Comment by hellonoam** [comment]
this is a bit weird. show/hide should work on mobile phones. It worked as
expected on my iphone simulator but not on the actual phone. I would just
see the login screen on top of the notes. and when I login the popup doesn't
disappear

**Comment by hellonoam** [comment]
seems like it's only failing on my iphone, maybe there's a safari bug with
the old ios
